// src/constants/routes.ts
export const ROUTES = {
  user: {
    signup: "/user/signup",
    login: "/user/login",
    verifyOtp: "/user/verifyOtp",
    resentOtp: "/user/resentOtp",
    forgotPassword: "/user/forgotPassword",
    recoveryPassword: "/user/recoveryPassword",
    verifyRecoveryPassword: "/user/verifyRecoveryPassword",
    resetPassword: (email: string) => `/user/resetPassword/${email}`,
    changePassword: (userId: string) => `/user/changePassword/${userId}`,
    refreshToken: "/user/refreshToken",
    updateProfile: (userId: string) => `/user/updateProfile/${userId}`,
    updateDp: (userId: string) => `/user/updateDp/${userId}`,
    logout: "/user/logout",
    doctors: "/user/doctors",
    conversation: (userId: string) => `/user/conversation/${userId}`,
    message: (conversationId: string) => `/user/message/${conversationId}`,
    sessions: "/user/sessions",
    stripe: {
      createOneTimePayment: "/user/stripe/create-one-time-payment",
    },
    getAppointments: "/user/getAppointments",
    me: "/user/me",
    doctorDetails: "/user/doctorDetails",
  },


  doctor: {
    signup: "/doctor/signup",
    login: "/doctor/login",
    verifyOtp: "/doctor/verifyOtp",
    resentOtp: "/doctor/resentOtp",
    refreshToken: "/doctor/refreshToken",
    logout: "/doctor/logout",
    stripe: {
      createCheckoutSession: "/doctor/stripe/create-checkout-session",
    },
    verifySubscription: "/doctor/verifySubscription",
    changePassword: (userId: string) => `/doctor/changePassword/${userId}`,
    updateProfile: (userId: string) => `/doctor/updateProfile/${userId}`,
    updateDp: (userId: string) => `/doctor/updateDp/${userId}`,
    conversation: (doctorId: string) => `/doctor/conversation/${doctorId}`,
    message: (conversationId: string) => `/doctor/message/${conversationId}`,
    sessions: "/doctor/sessions",
    getAppointments: "/doctor/getAppointments",
    me: "/doctor/me",
  },
  admin: {
    login: "/admin/login",
    forgotPassword: "/admin/forgotPassword",
    recoveryPassword: "/admin/recoveryPassword",
    resetPassword: (email: string) => `/admin/resetPassword/${email}`,
    refreshToken: "/admin/refreshToken",
    logout: "/admin/logout",
    users: "/admin/users",
    doctors: "/admin/doctors",
    doctor: (id: string) => `/admin/doctor/${id}`,
    verifyDoctor: (id: string) => `/admin/doctor/${id}/verify`,
    declineDoctor: (id: string) => `/admin/doctor/${id}/decline`,
    manageUsers: {
      block: (id: string) => `/admin/users/${id}/block`,
      unblock: (id: string) => `/admin/users/${id}/unblock`,
    },
    manageDoctors: {
      block: (id: string) => `/admin/doctors/${id}/block`,
      unblock: (id: string) => `/admin/doctors/${id}/unblock`,
    },
  },
};